koszyk/urls.py
from django.urls import path
from .views import cart_view, add_to_cart, checkout


app_name = 'koszyk'

urlpatterns = [
    path("", cart_view, name="cart_view"),
    path("add/<int:product_id>/", add_to_cart, name="add_to_cart"),
    path('checkout/', checkout, name='checkout'),
]

products/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'products'

urlpatterns = [
    path('', views.product_list_client, name='product_list_client'),
    path('produkty/<int:product_id>/dodaj/', views.add_to_cart, name='add_to_cart'),
    path('seller', views.product_list, name='product_list'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('create/', views.product_create, name='product_create'),
    path('edit/<int:pk>/', views.product_edit, name='product_edit'),
    path('delete/<int:pk>/', views.product_delete, name='product_delete'),
    path('increase_stock/<int:pk>/', views.increase_stock, name='increase_stock'),
    path('decrease_stock/<int:pk>/', views.decrease_stock, name='decrease_stock'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sklep_projekt/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('koszyk/', include('koszyk.urls')),
    path('', home, name='home')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout')
]

templates/base.html
<!DOCTYPE html>
<html lang="pl">
{% load static %}
{% if user.is_authenticated %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Moja Strona{% endblock %}</title>
    <link rel="stylesheet" href="{%static 'css/style.css'%}">

</head>
<body>
    <header>
        <h1 style="text-shadow: 
        -1px -1px 0 white,  
        1px -1px 0 white,
        -1px 1px 0 white,  
        1px 1px 0 white;" >DjangoShop</h1>
    </header>
    <nav>
        <a href ="/">Strona główna</a> |
        <a href="{% url 'products:product_list_client' %}">Lista produktów</a> |
        
        <a href="{% url 'koszyk:cart_view' %}">Koszyk</a> |

        <form id="logout-form" method="post" action="{% url 'logout' %}" style="display: inline;">
            {% csrf_token %}
            <a href="#" onclick="document.getElementById('logout-form').submit(); return false;">Wyloguj się</a>  |
        </form>

        {% if user.is_authenticated and user.role == "seller" %}
        <a href="{% url 'products:product_list' %}">Lista produktów dla sprzedawcy</a> |
        {% endif %}
    </nav>

    <main>
        {% block content %}{% endblock %}
    </main>
</body>
{% else %}
    <p>Nie jesteś zalogowany. <a href="{% url 'login' %}">Zaloguj się</a></p>
{% endif %}
</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <title>Strona główna</title>
</head>
<body>
    <h1 style="text-shadow: 
    -1px -1px 0 white,  
    1px -1px 0 white,
    -1px 1px 0 white,  
    1px 1px 0 white;" >DjangoShop</h1>
        {% if user.is_authenticated %}
        <nav>
        <a href ="/">Strona główna</a> |
        <a href="{% url 'products:product_list_client' %}">Lista produktów</a> |

        <a href="{% url 'koszyk:cart_view' %}">Koszyk</a> |

        <form id="logout-form" method="post" action="{% url 'logout' %}" style="display: inline;">
            {% csrf_token %}
            <a href="#" onclick="document.getElementById('logout-form').submit(); return false;">Wyloguj się</a>  |
        </form>

        {% if user.is_authenticated and user.role == "seller" %}
        <a href="{% url 'products:product_list' %}">Lista produktów dla sprzedawcy</a>
        {% endif %}
        </nav>

        <p>Witaj, {{ user.username }}! Zacznij zakupy już teraz. Zapoznaj się z 
            bogatą ofertą produktów w Liście Produktów.</p>

    {% else %}
    <p>Jeśli chcesz robić zakupy albo coś sprzedać zaloguj się
        lub zarejestruj, jeśli nie masz jeszcze konta.</p>
        <button onclick="window.location.href='{% url 'login' %}';">
            Zaloguj się
        </button>
        <button onclick="window.location.href='{% url 'register' %}';">
            Zarejestruj się
        </button>
    {% endif %}
</body>
</html>