koszyk/urls.py
from django.urls import path
from .views import cart_view, add_to_cart, checkout


app_name = 'koszyk'

urlpatterns = [
    path("", cart_view, name="cart_view"),
    path("add/<int:product_id>/", add_to_cart, name="add_to_cart"),
    path('checkout/', checkout, name='checkout'),
]

products/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'products'

urlpatterns = [
    path('', views.product_list_client, name='product_list_client'),
    path('produkty/<int:product_id>/dodaj/', views.add_to_cart, name='add_to_cart'),
    path('seller', views.product_list, name='product_list'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('create/', views.product_create, name='product_create'),
    path('edit/<int:pk>/', views.product_edit, name='product_edit'),
    path('delete/<int:pk>/', views.product_delete, name='product_delete'),
    path('increase_stock/<int:pk>/', views.increase_stock, name='increase_stock'),
    path('decrease_stock/<int:pk>/', views.decrease_stock, name='decrease_stock'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sklep_projekt/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('koszyk/', include('koszyk.urls')),
    path('', home, name='home')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout')
]

products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)  # Liczba dostępnych produktów
    image = models.ImageField(default='fallback.jpg', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def decrease_stock(self, amount=1):
        """Zmniejsza stan magazynowy o podaną ilość."""
        if self.stock >= amount:
            self.stock -= amount
            self.save()
            return True  # Udało się zmniejszyć stan magazynowy
        return False  # Brak wystarczającej ilości produktów

    def increase_stock(self, amount=1):
        """Zwiększa stan magazynowy o podaną ilość."""
        self.stock += amount
        self.save()

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'stock', 'image']

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Product
from .forms import ProductForm

def product_list(request):
    products = Product.objects.all()
    return render(request, 'products/product_list.html', {'products': products})

def product_list_client(request):
    products = Product.objects.all()
    return render(request, 'products/product_list_client.html', {'products': products})

def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'products/product_detail.html', {'product': product})


def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('products:product_list')
    else:
        form = ProductForm()
    return render(request, 'products/product_create.html', {'form': form})

def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:product_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'products/product_list.html', {'form': form})

def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return redirect('products:product_list')



def increase_stock(request, pk):
    """Zwiększa ilość danego produktu w magazynie."""
    product = get_object_or_404(Product, pk=pk)
    product.increase_stock(1)

    return redirect('products:product_list')

def decrease_stock(request, pk):
    """Zmniejsza ilość danego produktu w magazynie, jeśli to możliwe."""
    product = get_object_or_404(Product, pk=pk)
    return redirect('products:product_list')


def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == "POST":
        quantity = int(request.POST.get("quantity", 1))  

        if quantity > product.stock:  
            return redirect("products:product_detail", pk=product.id)

    return redirect("products:product_detail", pk=product.id)

products/templates/products/product_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h2>{% if form.instance.pk %}Edytuj produkt{% else %}Dodaj nowy produkt{% endif %}</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <table>
            {{ form.as_table }}
        </table>
        
        <button type="submit" class="btn btn-primary">
            {% if form.instance.pk %}Zapisz zmiany{% else %}Dodaj produkt{% endif %}
        </button>
    </form>

    <br>
    <a href="{% url 'products:product_list' %}" class="powrot">Powrót do listy produktów</a>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 class="nazwa">{{ product.name }}</h1>
  <div class="opis">
    <img class="image_detail" src="{{ product.image.url }}" alt="{{ product.name }}" />
    <div class="info_details">
      <p>{{ product.description }}</p>
      <p>Cena: {{ product.price }} PLN</p>
      <p>Liczba w magazynie: {{ product.stock }}</p>

      <!-- Wyświetlanie komunikatów -->
      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <div class="message">{{ message }}</div>
          {% endfor %}
        </div>
      {% endif %}

      <!-- Formularz dodawania do koszyka -->
      <form method="post" action="{% url 'koszyk:add_to_cart' product.id %}">
        {% csrf_token %}
        <label for="quantity">Ilość:</label>
        <input type="number" id="quantity" name="quantity" min="1" max="{{ product.stock }}" required>
        <button type="submit">Dodaj do koszyka</button>
      </form>
    </div>
  </div>

  <a href="{% url 'products:product_list_client' %}" class="powrot">Powrót do listy produktów</a>
{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h1>Lista produktów</h1>

  <ul>
    {% for product in products %}
      <li>
        <div class="info_list">
        {{ product.name }} - Liczba: {{ product.stock }}
        <a href="{% url 'products:increase_stock' pk=product.pk %}">+</a>
        <a href="{% url 'products:decrease_stock' pk=product.pk %}">-</a>
        </div>
        <!-- Przycisk usuwania -->
        <form action="{% url 'products:product_delete' pk=product.pk %}" method="post" >
          {% csrf_token %}
          <button type="submit" onclick="return confirm('Czy na pewno chcesz usunąć ten produkt?')">
            <span role="img" aria-label="Delete">
            🗑️
            </span>
          </button>
        </form>

      </li>
    {% endfor %}
  </ul>

  <a href="{% url 'products:product_create' %}" class="powrot">Dodaj nowy produkt</a>
{% endblock %}

products/templates/products/product_list_client.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <h2>Lista produktów</h2>

  <ul>
    {% for product in products %}
      <li>
        <p>
        <img
            class="image"
            src="{{ product.image.url }}"
            alt="{{ product.name }}"
        />
        </p>
        <a href="{% url 'products:product_detail' pk=product.pk %}" class="name"><h2>{{ product.name }}</h2></a>
        <div class="info">
        <p>Cena: {{ product.price }} PLN</p>
        <p>Liczba w magazynie: {{ product.stock }}</p>
        </div>
      </li>
    {% empty %}
      <p>Brak produktów w sklepie.</p>
    {% endfor %}
  </ul>
{% endblock %}